Repository Flexberry/NewPlatform.Flexberry.ORM.ODataService, pull requests merged in 2020-11, with the labels that each got.

#169 Feature update ms odata to 7.5.1
  .travis.yml
  NewPlatform.Flexberry.ORM.ODataService.Files/NewPlatform.Flexberry.ORM.ODataService.Files.csproj
  NewPlatform.Flexberry.ORM.ODataService.WebApi/NewPlatform.Flexberry.ORM.ODataService.WebApi.csproj
  NewPlatform.Flexberry.ORM.ODataService.nuspec
  NewPlatform.Flexberry.ORM.ODataService.sln
  NewPlatform.Flexberry.ORM.ODataService/Batch/DataObjectODataBatchHandler.cs
  NewPlatform.Flexberry.ORM.ODataService/Functions/QueryParameters.cs
  NewPlatform.Flexberry.ORM.ODataService/NewPlatform.Flexberry.ORM.ODataService.csproj
  NewPlatform.Flexberry.ORM.ODataServiceCore.Common/NewPlatform.Flexberry.ORM.ODataServiceCore.Common.csproj
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/NewPlatform.Flexberry.ORM.ODataServiceCore.Files.csproj
  NewPlatform.Flexberry.ORM.ODataServiceCore.WebApi/NewPlatform.Flexberry.ORM.ODataServiceCore.WebApi.csproj
  NewPlatform.Flexberry.ORM.ODataServiceCore/NewPlatform.Flexberry.ORM.ODataServiceCore.csproj
  Samples/ODataServiceSample.AspNet/ODataServiceSample.AspNet.csproj
  Samples/ODataServiceSample.AspNet/Web.config
  Samples/ODataServiceSample.AspNet/packages.config
  Samples/ODataServiceSample.AspNetCore/ODataServiceSample.AspNetCore.csproj
  Samples/ODataServiceSample.AspNetCore/Startup.cs
  Tests/BusinessServers/NewPlatform.Flexberry.ORM.ODataService.Tests.BusinessServers.csproj
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/App.config
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseIntegratedTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Create/BusinessServersTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Create/ChangeMasterInBSTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Create/CreateWithPseudoDetailDefinedTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/BuiltinQueryFunctionsTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/Excel/ExcelExportTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByMasterDetailFieldTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByMasterFieldTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterByPseudoDetailFieldTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/MetaDataTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/ReferenceToMasterTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/SkipTopOrderByTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/UtfRequestsTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/BusinessServersTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/ModifyDataTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/WebFileTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/AfterGetTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/AfterInternalServerErrorTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/AfterSaveTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/BeforeGetTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/BeforeSaveTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/ActionsTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/DelegateFunctionsTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Functions/FunctionsTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Model/CustomizationEdmModelNames.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Offline/DefaultOfflineManagerIntegratedTest.cs
  Tests/Objects/NewPlatform.Flexberry.ORM.ODataService.Tests.Objects.csproj
Labels: enhancement, refactoring

#153 Test date equality.
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Read/FilterTest.cs
Labels: bug

#172 Merge netstandard and netframework code.
  NewPlatform.Flexberry.ORM.ODataService.sln
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.Actions.cs
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.UserFunctions.cs
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
Labels: refactoring

#174 Merge nestandard and netframework odata files implementation
  NewPlatform.Flexberry.ORM.ODataService.Files/App.config
  NewPlatform.Flexberry.ORM.ODataService.Files/DefaultDataObjectFileAccessor.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/FileDescription.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/Helpers/Base64Helper.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/IDataObjectFileAccessor.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/MimeTypeUtils.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/NewPlatform.Flexberry.ORM.ODataService.Files.csproj
  NewPlatform.Flexberry.ORM.ODataService.Files/Providers/BaseDataObjectFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/Providers/DataObjectFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/Providers/DataObjectWebFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataService.Files/Providers/IDataObjectFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataService.WebApi/Controllers/BaseApiController.cs
  NewPlatform.Flexberry.ORM.ODataService.WebApi/Controllers/FileController.Download.cs
  NewPlatform.Flexberry.ORM.ODataService.WebApi/Controllers/FileController.Upload.cs
  NewPlatform.Flexberry.ORM.ODataService.WebApi/Controllers/FileController.cs
  NewPlatform.Flexberry.ORM.ODataService.WebApi/Controllers/LockController.cs
  NewPlatform.Flexberry.ORM.ODataService.WebApi/Extensions/HttpConfigurationExtensions.cs
  NewPlatform.Flexberry.ORM.ODataService.nuspec
  NewPlatform.Flexberry.ORM.ODataService.sln
  NewPlatform.Flexberry.ORM.ODataService/Controllers/BaseODataController.cs
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.cs
  NewPlatform.Flexberry.ORM.ODataService/DataObjectControllerActivator.cs
  NewPlatform.Flexberry.ORM.ODataService/NewPlatform.Flexberry.ORM.ODataService.csproj
  NewPlatform.Flexberry.ORM.ODataServiceCore.Common/NewPlatform.Flexberry.ORM.ODataServiceCore.Common.csproj
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/FileDescription.cs
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/NewPlatform.Flexberry.ORM.ODataServiceCore.Files.csproj
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/Providers/BaseDataObjectFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/Providers/DataObjectFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/Providers/DataObjectWebFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/Providers/IDataObjectFileProvider.cs
  NewPlatform.Flexberry.ORM.ODataServiceCore.Files/key.snk
  NewPlatform.Flexberry.ORM.ODataServiceCore.WebApi/Controllers/FileController.Download.cs
  NewPlatform.Flexberry.ORM.ODataServiceCore.WebApi/Controllers/FileController.Upload.cs
  NewPlatform.Flexberry.ORM.ODataServiceCore.WebApi/NewPlatform.Flexberry.ORM.ODataServiceCore.WebApi.csproj
  Samples/ODataServiceSample.AspNet/App_Start/ODataConfig.cs
  Samples/ODataServiceSample.AspNet/ODataServiceSample.AspNet.csproj
  Samples/ODataServiceSample.AspNet/Web.config
  Samples/ODataServiceSample.AspNet/packages.config
  Samples/ODataServiceSample.AspNetCore/ODataServiceSample.AspNetCore.csproj
  Samples/ODataServiceSample.AspNetCore/Startup.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/BaseODataServiceIntegratedTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/WebFileTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Files/FileControllerTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Files/FileDescriptionTest.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/NewPlatform.Flexberry.ORM.ODataService.Tests.csproj
Labels: refactoring

#176 Fix batch after update events
  NewPlatform.Flexberry.ORM.ODataService.nuspec
  NewPlatform.Flexberry.ORM.ODataService/Batch/DataObjectODataBatchHandler.cs
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.Events.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/Events/AfterSaveTest.cs
  Tests/Objects/Порода.cs
Labels: bug

#178 Fix batch update second detail with detail reference
  NewPlatform.Flexberry.ORM.ODataService/Controllers/DataObjectController.ModifyData.cs
  Tests/NewPlatform.Flexberry.ORM.ODataService.Tests/CRUD/Update/ModifyDataTest.cs
Labels: bug
